### ISSUE TITLE
install-command doesn't fail when lint fails

### ISSUE THREAD

**Issue by david-wb** [cypress-io/circleci-orb#334] opened 2021-02-20 05:49 UTC
## The orb does not work as expected

- what version of the orb are you currently using? `cypress-io/cypress@1`
  * maybe the problem has been fixed already, check the orb releases at [cypress-io/circleci-orb/releases](https://github.com/cypress-io/circleci-orb/releases)
- paste the `circle.yml` file if possible or at least the relevant portion
```
install-command: |
  set -eo pipefail
  echo $FIREBASE_SERVICE_ACCOUNT > ./serviceAccount.json 
  npm install
  npm run lint
 ```
- describe what you think should happen
The step should fail
- describe what happens
Doesn't fail
  * screenshots and links to the CircleCI builds would be great

When the `npm run lint` command fails, the `cypress/run` job doesn't fail.

**Comment by jordanpowell88** [comment] 2022-12-20 21:14
Closing as this is a duplicate of https://github.com/cypress-io/circleci-orb/issues/316

**Closed by jordanpowell88** 2022-12-20 21:14 UTC
