### ISSUE TITLE
Need ability to have start parameter take more than one command

### ISSUE THREAD

**Issue by desi** [cypress-io/circleci-orb#270] opened 2020-04-21 21:11 UTC
Our project has a frontend server and backend server (api). We use a mock api for the backend in cypress tests. We need to be able to run the mock server (to mimic backend api) and a front end server in Circle CI. 

Below is what I have tried but it isn't working so I am trying to figure out what I need to do to start that second server specifically on circleci
```
- cypress/run:
     executor: cypress/base-12-14-0
     yarn: true
     start: yarn start && yarn start-mockapi
```

I asked about this in the gitter chat and was directed to open a ticket as the start parameter likely doesn't handle passing both commands.

**Comment by desi** [comment] 2020-06-17 15:30
Hi @bahmutov just wondering if this is something you think might be addressed soon?

**Comment by desi** [comment] 2020-06-17 15:31
Hi @bahmutov just wondering if this is something you think might be addressed soon?

**Comment by desi** [comment] 2020-06-17 15:31
Hi @bahmutov just wondering if this is something you think might be addressed soon?

**Comment by desi** [comment] 2020-07-06 20:15
@jennifer-shehane Can you tell me a status on this?

**Comment by bahmutov** [comment] 2020-07-06 20:21
I don't have plans to implement this any time soon. I suggest using https://github.com/bahmutov/start-server-and-test maybe to start multiple services, wait for them to respond, then run tests.

**Comment by desi** [comment] 2020-07-06 20:49
Great. Thank you for the suggestion of a work around. Much appreciated!

**Comment by jordanpowell88** [comment] 2022-12-21 21:38
This is a duplicate of this issue https://github.com/cypress-io/circleci-orb/issues/313. Going to close

**Closed by jordanpowell88** 2022-12-21 21:38 UTC
