### ISSUE TITLE
Add timeouts

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/circleci-orb#41] opened 2018-11-28 17:23 UTC
For `wait-on` command and maybe for Cypress command?

Using CircleCI `no_output_timeout` option, probably do not even expose it to the user, just 5 minutes without stdout output and it is done

**Comment by elamperti** [comment] 2020-04-12 23:02
This would be useful, I've just ran a test where `yarn start` failed and wait-on was still waiting for the server after more than 6 minutes.

**Comment by jordanpowell88** [comment] 2022-12-21 22:01
Closing as this is a duplicate of https://github.com/cypress-io/circleci-orb/issues/316

**Closed by jordanpowell88** 2022-12-21 22:01 UTC
Labels: type: enhancement
